[package]
name = "arbitrary-signature-adr36"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = "1.5.3"
cosmwasm-schema = "1.1.5"
serde-cw-value = "0.7.0"
serde = "1.0.0"
serde-json-wasm = "1.0.1"