[package]
authors = ["Laurens Kubat <Laurens@Quasar.fi>"]
edition = "2021"
name = "lp-strategy"
version = "0.1.1"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmos-sdk-proto = {version = "0.15", default-features = false}
cosmwasm-schema = {version = "1.0.0"}
cosmwasm-std = {version = "1.5.0", features = ["abort", "stargate"]}
cw-storage-plus = "1.0.1"
cw-utils = "1.0.3"
cw2 = "1.1.2"
cw20 = "1.1.2"
cw20-base = {version = "1.1.2", features = ["library"]}
osmosis-std = {git = "https://github.com/quasar-finance/osmosis-rust.git"}
prost = {version = "0.11.9", default-features = false}
quasar-types = {path = "../../packages/quasar-types"}
schemars = "0.8.1"
serde = {version = "1.0.103", default-features = false, features = ["derive"]}
serde-json-wasm = {version = "1.0.0", default-features = false}
thiserror = {version = "1.0.23"}
uuid = {version = "1.1.2", default-features = false, features = ["v4", "js"]}

[dev-dependencies]
cw-multi-test = "0.20.0"
proptest = "1.0.0"
