[package]
edition = "2021"
name = "quasar-types"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }
osmosis-std = { workspace = true }
osmosis-std-derive = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus ={ workspace = true }
schemars ={ workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
prost = { workspace = true }
cw20 = { workspace = true }

cosmos-sdk-proto = {version = "0.15", default-features = false}
derive_more = {version = "0.99.17", default-features = false, features = [
  "display",
]}
rust_decimal = "1.24.0"
serde-json-wasm = {version = "0.4.1", default-features = false}
serde_test = "1.0"
