[workspace]

members = [
  # "contracts/icq",
  "contracts/airdrop",
  "contracts/lp-strategy", # "contracts/ibc-transfer",
  "contracts/basic-vault",
  "contracts/vault-rewards", # "contracts/intergamm-bindings-test",
  "contracts/multihop-router",
  "contracts/cl-vault", # "packages/intergamm-bindings",
  "packages/quasar-types",
]

exclude = [
  "contracts/cw-dex-router",
]

[workspace.dependencies]
cw-multi-test = {git = "https://github.com/njerschow/cw-multi-test.git"}
